[task]
mode = "ur"
num-client = 1
num-worker = 0

[multicast]
ip = "127.0.0.255"
variant = "halfsiphash"

[[replica]]
control-host = "127.0.0.1"
control-user = "cowsay"
ip = "127.0.0.1"

[[replica]]
control-host = "127.0.0.2"
control-user = "cowsay"
ip = "127.0.0.2"

[[replica]]
control-host = "127.0.0.3"
control-user = "cowsay"
ip = "127.0.0.3"

[[replica]]
control-host = "127.0.0.4"
control-user = "cowsay"
ip = "127.0.0.4"

[[client]]
control-host = "127.0.0.101"
control-user = "cowsay"
ip = "127.0.0.101"
